-- AlterTable
ALTER TABLE "pre_screening_templates" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "jobRequisitionId" TEXT;

-- CreateIndex
CREATE INDEX "pre_screening_templates_jobRequisitionId_idx" ON "pre_screening_templates"("jobRequisitionId");

-- AddForeignKey
ALTER TABLE "pre_screening_templates" ADD CONSTRAINT "pre_screening_templates_jobRequisitionId_fkey" FOREIGN KEY ("jobRequisitionId") REFERENCES "job_requisitions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
