'use client';

import { useState, useEffect } from 'react';
import {
  Plus,
  FileText,
  Trash2,
  Edit2,
  Copy,
  CheckCircle,
  XCircle,
  Clock,
  Loader2,
  ChevronDown,
  ChevronUp,
  AlertCircle,
  ClipboardList,
  Users,
  BarChart3,
} from 'lucide-react';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000';

// Types
type QuestionType = 'MULTIPLE_CHOICE' | 'TEXT' | 'YES_NO' | 'SCALE' | 'DATE';

interface Question {
  id?: string;
  questionText: string;
  questionType: QuestionType;
  options?: string[];
  isRequired: boolean;
  scoringWeight: number;
  idealAnswer?: string;
}

interface Template {
  id: string;
  name: string;
  description?: string;
  roleType?: string;
  companyName?: string;  // Company name for internal tracking (NOT shown to candidates)
  isActive: boolean;
  questions: Question[];
  createdAt: string;
  updatedAt: string;
  // Job requisition linkage
  jobRequisitionId?: string;
  isAutoGenerated?: boolean;
}

interface Response {
  id: string;
  templateId: string;
  conversationId: string;
  candidateName?: string;
  candidateEmail?: string;
  status: 'PENDING' | 'STARTED' | 'COMPLETED' | 'EXPIRED';
  submittedAt?: string;
  aiScore?: number;
  aiSummary?: string;
  aiFlags?: string[];
  createdAt: string;
}

// Default questions for new templates
const DEFAULT_QUESTIONS: Question[] = [
  {
    questionText: 'Are you legally authorized to work in the United States?',
    questionType: 'YES_NO',
    isRequired: true,
    scoringWeight: 3,
    idealAnswer: 'Yes',
  },
  {
    questionText: 'Will you now or in the future require visa sponsorship for employment?',
    questionType: 'YES_NO',
    isRequired: true,
    scoringWeight: 3,
    idealAnswer: 'No',
  },
  {
    questionText: 'What is your expected annual salary range?',
    questionType: 'MULTIPLE_CHOICE',
    options: [
      '$80,000 - $100,000',
      '$100,000 - $120,000',
      '$120,000 - $150,000',
      '$150,000 - $180,000',
      '$180,000+',
    ],
    isRequired: true,
    scoringWeight: 2,
  },
  {
    questionText: 'When would you be available to start?',
    questionType: 'MULTIPLE_CHOICE',
    options: [
      'Immediately',
      'Within 2 weeks',
      '2-4 weeks',
      '1-2 months',
      'More than 2 months',
    ],
    isRequired: true,
    scoringWeight: 1,
  },
  {
    questionText: 'Why are you interested in this opportunity?',
    questionType: 'TEXT',
    isRequired: true,
    scoringWeight: 1,
  },
];

export default function AssessmentsPage() {
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Create template modal state
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newTemplate, setNewTemplate] = useState({
    name: '',
    description: '',
    roleType: 'engineering',
    companyName: '',
    questions: [...DEFAULT_QUESTIONS],
  });
  const [creating, setCreating] = useState(false);

  // Expanded template state
  const [expandedTemplates, setExpandedTemplates] = useState<Set<string>>(new Set());

  // Link generation state
  const [generatingLink, setGeneratingLink] = useState<string | null>(null);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  // Fetch templates on mount
  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    try {
      setLoading(true);
      const res = await fetch(`${API_BASE}/api/assessments/templates`);
      const data = await res.json();

      if (data.success) {
        setTemplates(data.templates);
      } else {
        setError(data.error || 'Failed to fetch templates');
      }
    } catch (err) {
      console.error('Fetch error:', err);
      setError('Failed to connect to server');
    } finally {
      setLoading(false);
    }
  };

  const createTemplate = async () => {
    if (!newTemplate.name.trim()) {
      alert('Please enter a template name');
      return;
    }

    try {
      setCreating(true);
      const res = await fetch(`${API_BASE}/api/assessments/templates`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newTemplate),
      });

      const data = await res.json();

      if (data.success) {
        setTemplates((prev) => [data.template, ...prev]);
        setShowCreateModal(false);
        setNewTemplate({
          name: '',
          description: '',
          roleType: 'engineering',
          companyName: '',
          questions: [...DEFAULT_QUESTIONS],
        });
      } else {
        alert(data.error || 'Failed to create template');
      }
    } catch (err) {
      console.error('Create error:', err);
      alert('Failed to create template');
    } finally {
      setCreating(false);
    }
  };

  const deleteTemplate = async (id: string) => {
    if (!confirm('Are you sure you want to delete this template?')) return;

    try {
      const res = await fetch(`${API_BASE}/api/assessments/templates/${id}`, {
        method: 'DELETE',
      });

      const data = await res.json();

      if (data.success) {
        setTemplates((prev) => prev.filter((t) => t.id !== id));
      } else {
        alert(data.error || 'Failed to delete template');
      }
    } catch (err) {
      console.error('Delete error:', err);
      alert('Failed to delete template');
    }
  };

  const toggleExpanded = (id: string) => {
    setExpandedTemplates((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  // Generate a shareable assessment link (creates a generic response entry)
  const generateAndCopyLink = async (template: Template) => {
    setGeneratingLink(template.id);
    try {
      // Create a link with a generic conversation ID for manual sharing
      const conversationId = `manual-${Date.now()}`;

      const res = await fetch(`${API_BASE}/api/assessments/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          templateId: template.id,
          conversationId,
          candidateName: 'Candidate',
        }),
      });

      const data = await res.json();

      if (data.success && data.assessmentLink?.url) {
        // Copy to clipboard
        await navigator.clipboard.writeText(data.assessmentLink.url);
        setCopiedLink(template.id);
        setTimeout(() => setCopiedLink(null), 3000);

        // Show success message
        alert(`Assessment link copied to clipboard!\n\n${data.assessmentLink.url}\n\nExpires: ${new Date(data.assessmentLink.expiresAt).toLocaleDateString()}`);
      } else {
        alert(data.error || 'Failed to generate link');
      }
    } catch (err) {
      console.error('Generate link error:', err);
      alert('Failed to generate assessment link');
    } finally {
      setGeneratingLink(null);
    }
  };

  const addQuestion = () => {
    setNewTemplate((prev) => ({
      ...prev,
      questions: [
        ...prev.questions,
        {
          questionText: '',
          questionType: 'TEXT',
          isRequired: true,
          scoringWeight: 1,
        },
      ],
    }));
  };

  const updateQuestion = (index: number, updates: Partial<Question>) => {
    setNewTemplate((prev) => ({
      ...prev,
      questions: prev.questions.map((q, i) =>
        i === index ? { ...q, ...updates } : q
      ),
    }));
  };

  const removeQuestion = (index: number) => {
    setNewTemplate((prev) => ({
      ...prev,
      questions: prev.questions.filter((_, i) => i !== index),
    }));
  };

  // Loading state
  if (loading) {
    return (
      <div className="p-6">
        <div className="flex items-center justify-center h-64">
          <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <ClipboardList className="w-7 h-7 text-orange-500" />
            Assessment Templates
          </h1>
          <p className="text-gray-600 mt-1">
            Create and manage pre-screening questionnaires for candidates
          </p>
        </div>
        <button
          onClick={() => setShowCreateModal(true)}
          className="flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors"
        >
          <Plus className="w-5 h-5" />
          New Template
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-red-700">{error}</p>
            <button
              onClick={fetchTemplates}
              className="text-sm text-red-600 underline mt-1"
            >
              Retry
            </button>
          </div>
        </div>
      )}

      {/* Templates List */}
      {templates.length === 0 ? (
        <div className="text-center py-12 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200">
          <FileText className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900">No templates yet</h3>
          <p className="text-gray-500 mt-1">
            Create your first assessment template to start screening candidates
          </p>
          <button
            onClick={() => setShowCreateModal(true)}
            className="mt-4 inline-flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600"
          >
            <Plus className="w-5 h-5" />
            Create Template
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {templates.map((template) => (
            <div
              key={template.id}
              className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden"
            >
              {/* Template Header */}
              <div
                className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50"
                onClick={() => toggleExpanded(template.id)}
              >
                <div className="flex items-center gap-4">
                  <div
                    className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                      template.isActive
                        ? 'bg-green-100 text-green-600'
                        : 'bg-gray-100 text-gray-400'
                    }`}
                  >
                    <FileText className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900">
                      {template.name}
                    </h3>
                    <div className="flex items-center gap-3 text-sm text-gray-500">
                      <span>{template.questions.length} questions</span>
                      {template.roleType && (
                        <span className="px-2 py-0.5 bg-gray-100 rounded text-xs">
                          {template.roleType}
                        </span>
                      )}
                      {template.companyName && (
                        <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded text-xs">
                          {template.companyName}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {template.isAutoGenerated && (
                    <span className="px-2 py-0.5 bg-purple-100 text-purple-700 rounded text-xs">
                      AI
                    </span>
                  )}
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      generateAndCopyLink(template);
                    }}
                    disabled={generatingLink === template.id}
                    className="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors disabled:opacity-50"
                    title="Copy assessment link"
                  >
                    {generatingLink === template.id ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : copiedLink === template.id ? (
                      <CheckCircle className="w-4 h-4 text-green-600" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                  <span
                    className={`px-2 py-1 rounded-full text-xs font-medium ${
                      template.isActive
                        ? 'bg-green-100 text-green-700'
                        : 'bg-gray-100 text-gray-600'
                    }`}
                  >
                    {template.isActive ? 'Active' : 'Inactive'}
                  </span>
                  {expandedTemplates.has(template.id) ? (
                    <ChevronUp className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </div>
              </div>

              {/* Expanded Content */}
              {expandedTemplates.has(template.id) && (
                <div className="border-t border-gray-100 p-4">
                  {template.description && (
                    <p className="text-gray-600 mb-4">{template.description}</p>
                  )}

                  {/* Questions Preview */}
                  <div className="space-y-2 mb-4">
                    <h4 className="text-sm font-medium text-gray-700">
                      Questions
                    </h4>
                    {template.questions.map((q, i) => (
                      <div
                        key={q.id || i}
                        className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg"
                      >
                        <span className="w-6 h-6 bg-orange-100 text-orange-600 rounded flex items-center justify-center text-sm font-medium flex-shrink-0">
                          {i + 1}
                        </span>
                        <div className="flex-1 min-w-0">
                          <p className="text-gray-900">{q.questionText}</p>
                          <div className="flex items-center gap-2 mt-1 text-xs text-gray-500">
                            <span className="px-1.5 py-0.5 bg-gray-200 rounded">
                              {q.questionType}
                            </span>
                            {q.isRequired && (
                              <span className="text-red-500">Required</span>
                            )}
                            <span>Weight: {q.scoringWeight}</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center justify-between pt-4 border-t border-gray-100">
                    <div className="flex items-center gap-2">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          generateAndCopyLink(template);
                        }}
                        disabled={generatingLink === template.id}
                        className="flex items-center gap-2 px-3 py-2 bg-blue-50 text-blue-600 hover:bg-blue-100 rounded-lg transition-colors disabled:opacity-50"
                      >
                        {generatingLink === template.id ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : copiedLink === template.id ? (
                          <CheckCircle className="w-4 h-4" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                        {copiedLink === template.id ? 'Copied!' : 'Copy Link'}
                      </button>
                      {template.isAutoGenerated && (
                        <span className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">
                          AI Generated
                        </span>
                      )}
                    </div>
                    <button
                      onClick={() => deleteTemplate(template.id)}
                      className="flex items-center gap-2 px-3 py-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                    >
                      <Trash2 className="w-4 h-4" />
                      Delete
                    </button>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Create Template Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
            {/* Modal Header */}
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900">
                Create Assessment Template
              </h2>
              <p className="text-gray-600 mt-1">
                Set up questions to screen candidates before interviews
              </p>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              {/* Basic Info */}
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Template Name *
                  </label>
                  <input
                    type="text"
                    value={newTemplate.name}
                    onChange={(e) =>
                      setNewTemplate((prev) => ({ ...prev, name: e.target.value }))
                    }
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
                    placeholder="e.g., Senior Engineer Pre-Screen"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Description
                  </label>
                  <textarea
                    value={newTemplate.description}
                    onChange={(e) =>
                      setNewTemplate((prev) => ({
                        ...prev,
                        description: e.target.value,
                      }))
                    }
                    rows={2}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 resize-none"
                    placeholder="Brief description of this assessment..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Role Type
                  </label>
                  <select
                    value={newTemplate.roleType}
                    onChange={(e) =>
                      setNewTemplate((prev) => ({
                        ...prev,
                        roleType: e.target.value,
                      }))
                    }
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
                  >
                    <option value="engineering">Engineering</option>
                    <option value="product">Product</option>
                    <option value="design">Design</option>
                    <option value="sales">Sales</option>
                    <option value="marketing">Marketing</option>
                    <option value="operations">Operations</option>
                    <option value="other">Other</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Company Name (Internal Only)
                  </label>
                  <input
                    type="text"
                    value={newTemplate.companyName}
                    onChange={(e) =>
                      setNewTemplate((prev) => ({ ...prev, companyName: e.target.value }))
                    }
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
                    placeholder="e.g., Acme Corp (not visible to candidates)"
                  />
                  <p className="mt-1 text-xs text-gray-500">
                    This is for internal tracking only - candidates will NOT see this.
                  </p>
                </div>
              </div>

              {/* Questions */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <label className="text-sm font-medium text-gray-700">
                    Questions
                  </label>
                  <button
                    type="button"
                    onClick={addQuestion}
                    className="flex items-center gap-1 text-sm text-orange-600 hover:text-orange-700"
                  >
                    <Plus className="w-4 h-4" />
                    Add Question
                  </button>
                </div>

                <div className="space-y-4">
                  {newTemplate.questions.map((question, index) => (
                    <div
                      key={index}
                      className="p-4 bg-gray-50 rounded-lg border border-gray-200"
                    >
                      <div className="flex items-start justify-between gap-4">
                        <span className="w-6 h-6 bg-orange-500 text-white rounded flex items-center justify-center text-sm font-medium flex-shrink-0">
                          {index + 1}
                        </span>
                        <div className="flex-1 space-y-3">
                          <input
                            type="text"
                            value={question.questionText}
                            onChange={(e) =>
                              updateQuestion(index, {
                                questionText: e.target.value,
                              })
                            }
                            className="w-full px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
                            placeholder="Enter your question..."
                          />

                          <div className="grid grid-cols-3 gap-3">
                            <select
                              value={question.questionType}
                              onChange={(e) =>
                                updateQuestion(index, {
                                  questionType: e.target.value as QuestionType,
                                })
                              }
                              className="px-3 py-2 border border-gray-200 rounded-lg text-sm"
                            >
                              <option value="TEXT">Text</option>
                              <option value="YES_NO">Yes/No</option>
                              <option value="MULTIPLE_CHOICE">
                                Multiple Choice
                              </option>
                              <option value="SCALE">Scale (1-10)</option>
                              <option value="DATE">Date</option>
                            </select>

                            <div className="flex items-center gap-2">
                              <input
                                type="checkbox"
                                checked={question.isRequired}
                                onChange={(e) =>
                                  updateQuestion(index, {
                                    isRequired: e.target.checked,
                                  })
                                }
                                className="w-4 h-4 text-orange-500"
                              />
                              <span className="text-sm text-gray-600">
                                Required
                              </span>
                            </div>

                            <div className="flex items-center gap-2">
                              <span className="text-sm text-gray-600">
                                Weight:
                              </span>
                              <input
                                type="number"
                                min="1"
                                max="5"
                                value={question.scoringWeight}
                                onChange={(e) =>
                                  updateQuestion(index, {
                                    scoringWeight: parseInt(e.target.value) || 1,
                                  })
                                }
                                className="w-16 px-2 py-1 border border-gray-200 rounded text-sm"
                              />
                            </div>
                          </div>

                          {question.questionType === 'MULTIPLE_CHOICE' && (
                            <input
                              type="text"
                              value={question.options?.join(', ') || ''}
                              onChange={(e) =>
                                updateQuestion(index, {
                                  options: e.target.value
                                    .split(',')
                                    .map((s) => s.trim())
                                    .filter(Boolean),
                                })
                              }
                              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"
                              placeholder="Options (comma-separated)"
                            />
                          )}

                          <input
                            type="text"
                            value={question.idealAnswer || ''}
                            onChange={(e) =>
                              updateQuestion(index, {
                                idealAnswer: e.target.value,
                              })
                            }
                            className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"
                            placeholder="Ideal answer (for scoring)"
                          />
                        </div>

                        <button
                          type="button"
                          onClick={() => removeQuestion(index)}
                          className="p-1 text-gray-400 hover:text-red-500"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-6 border-t border-gray-200 flex items-center justify-end gap-3">
              <button
                onClick={() => setShowCreateModal(false)}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={createTemplate}
                disabled={creating || !newTemplate.name.trim()}
                className="flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {creating ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <Plus className="w-5 h-5" />
                )}
                Create Template
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
