'use client';

import { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import {
  MessageSquare,
  User,
  AlertTriangle,
  Clock,
  Send,
  RefreshCw,
  ChevronRight,
  ExternalLink,
  Bot,
  UserCheck,
  CheckCircle,
  Loader2,
  Plus,
  X,
  ClipboardList,
} from 'lucide-react';
import AssessmentResultCard from '../../components/AssessmentResultCard';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000';

// =============================================================================
// TYPES
// =============================================================================

interface ConversationMessage {
  id: string;
  role: 'riley' | 'candidate' | 'teleoperator';
  content: string;
  timestamp: string;
  metadata?: {
    isAutoGenerated?: boolean;
    wasEscalated?: boolean;
  };
}

interface Conversation {
  id: string;
  chatId: string;
  candidateName: string;
  candidateTitle?: string;
  candidateCompany?: string;
  candidateProfileUrl?: string;
  candidatePictureUrl?: string;
  jobTitle?: string;
  stage: string;
  status: 'active' | 'paused' | 'completed' | 'escalated';
  escalationReason?: string;
  messages: ConversationMessage[];
  lastMessageAt: string;
  lastMessageBy: 'riley' | 'candidate' | 'teleoperator';
}

interface PendingMessage {
  id: string;
  chatId: string;
  senderName?: string;
  messageText?: string;
  timestamp: string;
  type: 'message_received' | 'escalation_required';
}

interface UnipileConfig {
  apiKey: string;
  dsn: string;
  port: string;
  accountId: string;
}

// =============================================================================
// COMPONENT
// =============================================================================

function ConversationsPageContent() {
  const searchParams = useSearchParams();
  const targetChatId = searchParams.get('chatId');
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [pendingMessages, setPendingMessages] = useState<PendingMessage[]>([]);
  const [selectedConversation, setSelectedConversation] = useState<Conversation | null>(null);
  const [replyText, setReplyText] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSending, setIsSending] = useState(false);
  const [unipileConfig, setUnipileConfig] = useState<UnipileConfig | null>(null);
  const [stats, setStats] = useState<{
    total: number;
    needingResponse: number;
    escalated: number;
  } | null>(null);

  // New conversation modal state
  const [showNewConversationModal, setShowNewConversationModal] = useState(false);
  const [newConversationUrl, setNewConversationUrl] = useState('');
  const [newConversationMessage, setNewConversationMessage] = useState('');
  const [isStartingConversation, setIsStartingConversation] = useState(false);

  // Assessment state
  const [assessmentTemplates, setAssessmentTemplates] = useState<{ id: string; name: string }[]>([]);
  const [selectedAssessment, setSelectedAssessment] = useState<unknown>(null);
  const [loadingAssessment, setLoadingAssessment] = useState(false);

  // Load Unipile config from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('riley_unipile_config');
    if (saved) {
      try {
        setUnipileConfig(JSON.parse(saved));
      } catch {
        console.error('Failed to parse Unipile config');
      }
    }
  }, []);

  // Auto-select conversation from URL query param (deep-link from Queue page)
  useEffect(() => {
    if (targetChatId && conversations.length > 0 && !selectedConversation) {
      const target = conversations.find((c) => c.chatId === targetChatId);
      if (target) {
        setSelectedConversation(target);
        console.log('[Conversations] Auto-selected conversation from URL:', targetChatId);
      }
    }
  }, [targetChatId, conversations, selectedConversation]);

  // Fetch conversations and pending messages
  const fetchData = useCallback(async () => {
    setIsLoading(true);
    try {
      // Fetch pending webhook events
      const pendingRes = await fetch(`${API_BASE}/webhooks/pending`);
      if (pendingRes.ok) {
        const pendingData = await pendingRes.json();
        setPendingMessages(pendingData.pending || []);
      }

      // First, try to fetch from Riley conversations database (Riley-initiated only)
      // This is the preferred source as it only shows conversations Riley started
      try {
        const rileyConvsRes = await fetch(`${API_BASE}/webhooks/riley-conversations?limit=50`);
        if (rileyConvsRes.ok) {
          const rileyData = await rileyConvsRes.json();
          if (rileyData.success && rileyData.conversations?.length > 0) {
            // Use Riley conversations from database
            const rileyConvs = rileyData.conversations.map((conv: Conversation) => ({
              ...conv,
              candidateName: conv.candidateName || 'LinkedIn User',
            }));

            setConversations(rileyConvs);

            // Fetch stats
            const statsRes = await fetch(`${API_BASE}/webhooks/riley-conversations-stats`);
            if (statsRes.ok) {
              const statsData = await statsRes.json();
              setStats({
                total: statsData.stats?.total || rileyConvs.length,
                needingResponse: statsData.stats?.awaitingResponse || 0,
                escalated: statsData.stats?.escalated || 0,
              });
            } else {
              setStats({
                total: rileyConvs.length,
                needingResponse: rileyConvs.filter((c: Conversation) => c.lastMessageBy === 'candidate').length,
                escalated: rileyConvs.filter((c: Conversation) => c.status === 'escalated').length,
              });
            }

            console.log('[Conversations] Loaded', rileyConvs.length, 'Riley-initiated conversations from database');
            return;
          }
        }
      } catch (dbError) {
        console.log('[Conversations] Could not fetch from database, falling back to Unipile:', dbError);
      }

      // Fallback: If we have Unipile config, fetch all LinkedIn conversations
      // Note: This shows ALL conversations, not just Riley-initiated ones
      if (unipileConfig) {
        const linkedinRes = await fetch(`${API_BASE}/webhooks/linkedin/chats`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ unipileConfig, limit: 20 }),
        });

        if (linkedinRes.ok) {
          const linkedinData = await linkedinRes.json();
          const linkedinConvs = (linkedinData.conversations || []).map((conv: {
            id: string;
            chatId: string;
            candidateName: string;
            candidateProfileUrl?: string;
            candidatePictureUrl?: string;
            lastMessageAt: string;
            unreadCount: number;
            messages: Array<{ id: string; role: string; content: string; timestamp: string }>;
          }) => {
            // Sort messages chronologically (oldest first for display)
            const sortedMessages = [...conv.messages].sort((a, b) => {
              const dateA = new Date(a.timestamp).getTime() || 0;
              const dateB = new Date(b.timestamp).getTime() || 0;
              return dateA - dateB;
            });

            // Get the most recent message to determine lastMessageBy
            const mostRecentMsg = sortedMessages[sortedMessages.length - 1];

            return {
              ...conv,
              candidateName: conv.candidateName || 'LinkedIn User',
              messages: sortedMessages,
              stage: 'in_conversation',
              status: conv.unreadCount > 0 ? 'needs_response' : 'active',
              lastMessageBy: mostRecentMsg?.role === 'candidate' ? 'candidate' : 'riley',
            };
          });

          setConversations(linkedinConvs);

          // Calculate stats
          setStats({
            total: linkedinConvs.length,
            needingResponse: linkedinConvs.filter((c: { unreadCount: number }) => c.unreadCount > 0).length,
            escalated: 0,
          });
          console.log('[Conversations] Loaded', linkedinConvs.length, 'conversations from Unipile (all conversations)');
          return;
        }
      }

      // Fallback: Fetch from webhook events if no Unipile config
      const eventsRes = await fetch(`${API_BASE}/webhooks/conversations`);
      if (eventsRes.ok) {
        const eventsData = await eventsRes.json();
        // Transform events into conversation-like structure for display
        // In production, this would come from the database
        const events = eventsData.events || [];

        // Group events by chatId to create conversation summaries
        const chatMap = new Map<string, Conversation>();
        for (const event of events) {
          if (!chatMap.has(event.chatId)) {
            chatMap.set(event.chatId, {
              id: event.chatId,
              chatId: event.chatId,
              candidateName: event.senderName || event.metadata?.recipientName || 'Unknown',
              candidateProfileUrl: event.senderProfileUrl,
              stage: 'in_conversation',
              status: event.type === 'escalation_required' ? 'escalated' : 'active',
              messages: [],
              lastMessageAt: event.timestamp,
              lastMessageBy: event.type === 'message_received' ? 'candidate' : 'riley',
            });
          }

          const conv = chatMap.get(event.chatId)!;
          conv.messages.push({
            id: event.id,
            role: event.type === 'message_received' ? 'candidate' : 'riley',
            content: event.messageText || '',
            timestamp: event.timestamp,
          });
        }

        setConversations(Array.from(chatMap.values()));

        // Calculate stats
        const convList = Array.from(chatMap.values());
        setStats({
          total: convList.length,
          needingResponse: convList.filter(c => c.lastMessageBy === 'candidate' && c.status === 'active').length,
          escalated: convList.filter(c => c.status === 'escalated').length,
        });
      }
    } catch (error) {
      console.error('Failed to fetch conversations:', error);
    } finally {
      setIsLoading(false);
    }
  }, [unipileConfig]);

  useEffect(() => {
    fetchData();
    // Poll for updates every 30 seconds
    const interval = setInterval(fetchData, 30000);
    return () => clearInterval(interval);
  }, [fetchData]);

  // Fetch assessment templates
  useEffect(() => {
    async function fetchTemplates() {
      try {
        const res = await fetch(`${API_BASE}/api/assessments/templates?activeOnly=true`);
        const data = await res.json();
        if (data.success) {
          setAssessmentTemplates(data.templates.map((t: { id: string; name: string }) => ({ id: t.id, name: t.name })));
        }
      } catch (err) {
        console.error('Failed to fetch assessment templates:', err);
      }
    }
    fetchTemplates();
  }, []);

  // Fetch assessment for selected conversation
  useEffect(() => {
    async function fetchAssessment() {
      if (!selectedConversation) {
        setSelectedAssessment(null);
        return;
      }
      setLoadingAssessment(true);
      try {
        const res = await fetch(`${API_BASE}/api/assessments/conversation/${selectedConversation.id}`);
        const data = await res.json();
        if (data.success) {
          setSelectedAssessment(data.assessment);
        } else {
          setSelectedAssessment(null);
        }
      } catch (err) {
        console.error('Failed to fetch assessment:', err);
        setSelectedAssessment(null);
      } finally {
        setLoadingAssessment(false);
      }
    }
    fetchAssessment();
  }, [selectedConversation]);

  // Send assessment to candidate
  const sendAssessment = async (templateId: string) => {
    if (!selectedConversation) return;
    try {
      const res = await fetch(`${API_BASE}/api/assessments/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          templateId,
          conversationId: selectedConversation.id,
          candidateName: selectedConversation.candidateName,
        }),
      });
      const data = await res.json();
      if (data.success && data.assessmentLink?.url) {
        // Copy link to clipboard and show in chat
        navigator.clipboard.writeText(data.assessmentLink.url);
        alert(`Assessment link copied to clipboard!\n\n${data.assessmentLink.url}\n\nSend this link to the candidate.`);
        // Refresh assessment data
        setSelectedAssessment(null);
        const refreshRes = await fetch(`${API_BASE}/api/assessments/conversation/${selectedConversation.id}`);
        const refreshData = await refreshRes.json();
        if (refreshData.success) {
          setSelectedAssessment(refreshData.assessment);
        }
      } else {
        alert(data.error || 'Failed to create assessment link');
      }
    } catch (err) {
      console.error('Failed to send assessment:', err);
      alert('Failed to send assessment');
    }
  };

  // Send a reply
  const sendReply = async () => {
    if (!selectedConversation || !replyText.trim() || !unipileConfig) return;

    setIsSending(true);
    try {
      const response = await fetch(
        `${API_BASE}/webhooks/conversations/${selectedConversation.chatId}/respond`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            message: replyText,
            unipileConfig,
          }),
        }
      );

      if (response.ok) {
        setReplyText('');
        // Refresh data
        await fetchData();
      } else {
        const error = await response.json();
        alert(`Failed to send: ${error.error}`);
      }
    } catch (error) {
      console.error('Failed to send reply:', error);
      alert('Failed to send reply');
    } finally {
      setIsSending(false);
    }
  };

  // Dismiss a pending message
  const dismissMessage = async (chatId: string) => {
    try {
      await fetch(`${API_BASE}/webhooks/conversations/${chatId}/dismiss`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason: 'Manually dismissed by teleoperator' }),
      });
      await fetchData();
    } catch (error) {
      console.error('Failed to dismiss:', error);
    }
  };

  // Start a new conversation
  const startNewConversation = async () => {
    if (!newConversationUrl.trim() || !newConversationMessage.trim() || !unipileConfig) return;

    setIsStartingConversation(true);
    try {
      const response = await fetch(`${API_BASE}/webhooks/conversations/new`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipientProfileUrl: newConversationUrl,
          message: newConversationMessage,
          unipileConfig,
        }),
      });

      const data = await response.json();

      if (data.success) {
        // Reset form and close modal
        setNewConversationUrl('');
        setNewConversationMessage('');
        setShowNewConversationModal(false);
        // Refresh data to show the new conversation
        await fetchData();
        alert('Message sent successfully!');
      } else {
        alert(`Failed to send: ${data.error}`);
      }
    } catch (error) {
      console.error('Failed to start conversation:', error);
      alert('Failed to start conversation');
    } finally {
      setIsStartingConversation(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'escalated':
        return (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
            <AlertTriangle className="w-3 h-3" />
            Escalated
          </span>
        );
      case 'active':
        return (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
            <CheckCircle className="w-3 h-3" />
            Active
          </span>
        );
      case 'completed':
        return (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
            <UserCheck className="w-3 h-3" />
            Completed
          </span>
        );
      default:
        return (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-600">
            {status}
          </span>
        );
    }
  };

  const formatTime = (timestamp: string | undefined | null) => {
    if (!timestamp) return 'Recently';

    const date = new Date(timestamp);

    // Check if date is valid
    if (isNaN(date.getTime())) {
      return 'Recently';
    }

    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 0) return 'Just now'; // Future dates (clock skew)
    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  return (
    <div className="p-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Conversations</h1>
          <p className="text-gray-600 mt-1">
            Manage candidate conversations and respond to messages
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowNewConversationModal(true)}
            disabled={!unipileConfig}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <Plus className="w-4 h-4" />
            New Conversation
          </button>
          <button
            onClick={fetchData}
            disabled={isLoading}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      {stats && (
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-100 rounded-lg">
                <MessageSquare className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
                <p className="text-sm text-gray-600">Total Conversations</p>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-yellow-100 rounded-lg">
                <Clock className="w-5 h-5 text-yellow-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900">{stats.needingResponse}</p>
                <p className="text-sm text-gray-600">Awaiting Response</p>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-red-100 rounded-lg">
                <AlertTriangle className="w-5 h-5 text-red-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900">{stats.escalated}</p>
                <p className="text-sm text-gray-600">Escalated</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Unipile Config Warning */}
      {!unipileConfig && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-600 mt-0.5" />
            <div>
              <p className="font-medium text-yellow-800">LinkedIn Not Connected</p>
              <p className="text-sm text-yellow-700 mt-1">
                Connect your LinkedIn account in{' '}
                <a href="/settings" className="underline">
                  Settings
                </a>{' '}
                to send replies.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Main Content */}
      <div className="grid grid-cols-3 gap-6">
        {/* Conversation List */}
        <div className="col-span-1 bg-white rounded-lg border border-gray-200 overflow-hidden">
          <div className="p-4 border-b border-gray-200">
            <h2 className="font-semibold text-gray-900">All Conversations</h2>
          </div>
          <div className="divide-y divide-gray-100 max-h-[600px] overflow-y-auto">
            {isLoading && conversations.length === 0 ? (
              <div className="p-8 text-center text-gray-500">
                <Loader2 className="w-6 h-6 animate-spin mx-auto mb-2" />
                Loading conversations...
              </div>
            ) : conversations.length === 0 ? (
              <div className="p-8 text-center text-gray-500">
                <MessageSquare className="w-8 h-8 mx-auto mb-2 text-gray-400" />
                <p>No conversations yet</p>
                <p className="text-sm mt-1">
                  Start sourcing candidates to begin conversations
                </p>
              </div>
            ) : (
              conversations.map((conv) => (
                <button
                  key={conv.id}
                  onClick={() => setSelectedConversation(conv)}
                  className={`w-full p-4 text-left hover:bg-gray-50 transition-colors ${
                    selectedConversation?.id === conv.id ? 'bg-blue-50' : ''
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-3">
                      {conv.candidatePictureUrl ? (
                        <img
                          src={conv.candidatePictureUrl}
                          alt={conv.candidateName}
                          className="w-10 h-10 rounded-full object-cover"
                          onError={(e) => {
                            // Fallback to User icon if image fails to load
                            e.currentTarget.style.display = 'none';
                            e.currentTarget.nextElementSibling?.classList.remove('hidden');
                          }}
                        />
                      ) : null}
                      <div className={`w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center ${conv.candidatePictureUrl ? 'hidden' : ''}`}>
                        <User className="w-5 h-5 text-gray-600" />
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{conv.candidateName}</p>
                        {conv.candidateTitle && (
                          <p className="text-sm text-gray-600 truncate max-w-[150px]">
                            {conv.candidateTitle}
                          </p>
                        )}
                      </div>
                    </div>
                    <ChevronRight className="w-4 h-4 text-gray-400 mt-1" />
                  </div>
                  <div className="flex items-center justify-between mt-2">
                    <div className="flex items-center gap-1.5">
                      {getStatusBadge(conv.status)}
                      {conv.lastMessageBy === 'candidate' && conv.status === 'active' && (
                        <span className="inline-flex items-center px-1.5 py-0.5 rounded-full text-[10px] font-semibold bg-yellow-100 text-yellow-800">
                          New Reply
                        </span>
                      )}
                    </div>
                    <span className="text-xs text-gray-500">
                      {formatTime(conv.lastMessageAt)}
                    </span>
                  </div>
                  {conv.messages.length > 0 && (
                    <p className="text-sm text-gray-600 mt-2 truncate">
                      {conv.messages[conv.messages.length - 1]?.content}
                    </p>
                  )}
                </button>
              ))
            )}
          </div>
        </div>

        {/* Conversation Detail */}
        <div className="col-span-2 bg-white rounded-lg border border-gray-200 overflow-hidden flex flex-col">
          {selectedConversation ? (
            <>
              {/* Header */}
              <div className="p-4 border-b border-gray-200">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    {selectedConversation.candidatePictureUrl ? (
                      <img
                        src={selectedConversation.candidatePictureUrl}
                        alt={selectedConversation.candidateName}
                        className="w-10 h-10 rounded-full object-cover"
                        onError={(e) => {
                          e.currentTarget.style.display = 'none';
                          e.currentTarget.nextElementSibling?.classList.remove('hidden');
                        }}
                      />
                    ) : null}
                    <div className={`w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center ${selectedConversation.candidatePictureUrl ? 'hidden' : ''}`}>
                      <User className="w-5 h-5 text-gray-600" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900">
                        {selectedConversation.candidateName}
                      </p>
                      <p className="text-sm text-gray-600">
                        {selectedConversation.candidateTitle}
                        {selectedConversation.candidateCompany &&
                          ` at ${selectedConversation.candidateCompany}`}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {getStatusBadge(selectedConversation.status)}
                    {selectedConversation.candidateProfileUrl && (
                      <a
                        href={selectedConversation.candidateProfileUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                        title="View LinkedIn Profile"
                      >
                        <ExternalLink className="w-4 h-4 text-gray-600" />
                      </a>
                    )}
                  </div>
                </div>
                {selectedConversation.escalationReason && (
                  <div className="mt-3 p-3 bg-red-50 rounded-lg">
                    <p className="text-sm text-red-800">
                      <strong>Escalation Reason:</strong>{' '}
                      {selectedConversation.escalationReason}
                    </p>
                  </div>
                )}

                {/* Assessment Card */}
                <div className="mt-3">
                  {loadingAssessment ? (
                    <div className="flex items-center gap-2 text-gray-500 text-sm">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Loading assessment...
                    </div>
                  ) : (
                    <AssessmentResultCard
                      conversationId={selectedConversation.id}
                      assessment={selectedAssessment as Parameters<typeof AssessmentResultCard>[0]['assessment']}
                      templates={assessmentTemplates}
                      onSendAssessment={sendAssessment}
                    />
                  )}
                </div>
              </div>

              {/* Messages */}
              <div className="flex-1 p-4 overflow-y-auto space-y-4 bg-gray-50">
                {selectedConversation.messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex ${
                      msg.role === 'candidate' ? 'justify-start' : 'justify-end'
                    }`}
                  >
                    <div
                      className={`max-w-[70%] rounded-2xl px-4 py-2 ${
                        msg.role === 'candidate'
                          ? 'bg-white border border-gray-200 rounded-bl-md'
                          : msg.role === 'riley'
                          ? 'bg-blue-600 text-white rounded-br-md'
                          : 'bg-purple-600 text-white rounded-br-md'
                      }`}
                    >
                      <div className="flex items-center gap-2 mb-1">
                        {msg.role === 'riley' && (
                          <Bot className="w-3 h-3" />
                        )}
                        <span className="text-xs opacity-75">
                          {msg.role === 'candidate'
                            ? selectedConversation.candidateName
                            : msg.role === 'riley'
                            ? 'Riley'
                            : 'You'}
                        </span>
                      </div>
                      <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                      <p className="text-xs mt-1 opacity-60">
                        {formatTime(msg.timestamp)}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Reply Input */}
              <div className="p-4 border-t border-gray-200">
                <div className="flex items-end gap-2">
                  <textarea
                    value={replyText}
                    onChange={(e) => setReplyText(e.target.value)}
                    placeholder={
                      unipileConfig
                        ? 'Type your reply...'
                        : 'Connect LinkedIn in Settings to reply'
                    }
                    disabled={!unipileConfig || isSending}
                    rows={2}
                    className="flex-1 resize-none rounded-lg border border-gray-200 px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                  />
                  <button
                    onClick={sendReply}
                    disabled={!unipileConfig || !replyText.trim() || isSending}
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-2"
                  >
                    {isSending ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Send className="w-4 h-4" />
                    )}
                    Send
                  </button>
                </div>
              </div>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center text-gray-500">
              <div className="text-center">
                <MessageSquare className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p className="font-medium">Select a conversation</p>
                <p className="text-sm mt-1">
                  Choose a conversation from the list to view messages
                </p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Pending Messages Section */}
      {pendingMessages.length > 0 && (
        <div className="mt-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">
            Pending Messages ({pendingMessages.length})
          </h2>
          <div className="space-y-3">
            {pendingMessages.map((msg) => (
              <div
                key={msg.id}
                className={`bg-white rounded-lg border p-4 ${
                  msg.type === 'escalation_required'
                    ? 'border-red-200 bg-red-50'
                    : 'border-gray-200'
                }`}
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center">
                      <User className="w-5 h-5 text-gray-600" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900">
                        {msg.senderName || 'Unknown Sender'}
                      </p>
                      <p className="text-sm text-gray-600 mt-1">{msg.messageText}</p>
                      <p className="text-xs text-gray-500 mt-1">
                        {formatTime(msg.timestamp)}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {msg.type === 'escalation_required' && (
                      <span className="text-xs text-red-600 font-medium">
                        Needs Review
                      </span>
                    )}
                    <button
                      onClick={() => {
                        // Find or create conversation and open it
                        const conv = conversations.find((c) => c.chatId === msg.chatId);
                        if (conv) {
                          setSelectedConversation(conv);
                        }
                      }}
                      className="px-3 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition-colors"
                    >
                      Respond
                    </button>
                    <button
                      onClick={() => dismissMessage(msg.chatId)}
                      className="px-3 py-1.5 bg-gray-100 text-gray-700 text-sm rounded-lg hover:bg-gray-200 transition-colors"
                    >
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* New Conversation Modal */}
      {showNewConversationModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">New Conversation</h2>
              <button
                onClick={() => {
                  setShowNewConversationModal(false);
                  setNewConversationUrl('');
                  setNewConversationMessage('');
                }}
                className="p-1 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="w-5 h-5 text-gray-500" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="p-4 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  LinkedIn Profile URL
                </label>
                <input
                  type="text"
                  value={newConversationUrl}
                  onChange={(e) => setNewConversationUrl(e.target.value)}
                  placeholder="https://linkedin.com/in/username"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Paste the full LinkedIn profile URL of the person you want to message
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Message
                </label>
                <textarea
                  value={newConversationMessage}
                  onChange={(e) => setNewConversationMessage(e.target.value)}
                  placeholder="Hi! I wanted to reach out about..."
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                />
              </div>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                <p className="text-sm text-blue-800">
                  <strong>Note:</strong> This will send a LinkedIn message directly. If you&apos;re not
                  connected with this person, it may be sent as a connection request with a note
                  (limited to 300 characters).
                </p>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="flex items-center justify-end gap-2 p-4 border-t border-gray-200">
              <button
                onClick={() => {
                  setShowNewConversationModal(false);
                  setNewConversationUrl('');
                  setNewConversationMessage('');
                }}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={startNewConversation}
                disabled={!newConversationUrl.trim() || !newConversationMessage.trim() || isStartingConversation}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {isStartingConversation ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Sending...
                  </>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    Send Message
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Wrap with Suspense for Next.js App Router useSearchParams() requirement
export default function ConversationsPage() {
  return (
    <Suspense fallback={
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
      </div>
    }>
      <ConversationsPageContent />
    </Suspense>
  );
}
