/**
 * Task - Core of the Two-Loop System
 *
 * Tasks represent operations that Riley generates through the inner loop.
 * They can be either:
 * - Sandbox (draft): Generated but not executed, can be freely revised
 * - Effectful: Have real-world impact, require approval before execution
 *
 * The escalation system determines when human teleoperators need to review.
 */

import type { EscalationReasonType } from './Guidelines.js';

// =============================================================================
// TASK TYPES AND PAYLOADS
// =============================================================================

export type TaskType =
  // Outreach
  | 'SEND_EMAIL'
  | 'SEND_LINKEDIN_MESSAGE'
  | 'SEND_FOLLOW_UP'
  // Sourcing
  | 'SEARCH_CANDIDATES'
  | 'IMPORT_CANDIDATE'
  // Screening
  | 'SCREEN_RESUME'
  | 'GENERATE_ASSESSMENT'
  // Scheduling
  | 'SCHEDULE_INTERVIEW'
  | 'SEND_REMINDER'
  // ATS
  | 'UPDATE_ATS_STATUS'
  | 'SYNC_CANDIDATE'
  // Offers
  | 'PREPARE_OFFER'
  | 'SEND_OFFER'
  // Internal
  | 'UPDATE_GUIDELINES'
  | 'GENERATE_REPORT';

export type TaskStatus =
  | 'DRAFT' // Generated by inner loop, not yet queued
  | 'PENDING_APPROVAL' // Awaiting teleoperator review
  | 'APPROVED' // Approved, waiting execution
  | 'EXECUTING' // Currently being executed
  | 'COMPLETED' // Successfully executed
  | 'FAILED' // Execution failed
  | 'REJECTED' // Rejected by teleoperator
  | 'CANCELLED' // Cancelled before execution
  | 'EXPIRED'; // Passed expiration time

export type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

// =============================================================================
// TASK PAYLOADS BY TYPE
// =============================================================================

export interface SendEmailPayload {
  candidateId: string;
  conversationId?: string;
  to: string;
  cc?: string[];
  bcc?: string[];
  subject: string;
  body: string;
  templateId?: string;
  attachments?: Attachment[];
}

export interface SendLinkedInMessagePayload {
  candidateId: string;
  conversationId?: string;
  linkedInProfileUrl: string;
  message: string;
  templateId?: string;
}

export interface SendFollowUpPayload {
  candidateId: string;
  conversationId: string;
  channel: 'email' | 'linkedin';
  message: string;
  followUpNumber: number;
  templateId?: string;
}

export interface SearchCandidatesPayload {
  requisitionId: string;
  searchQuery: CandidateSearchQuery;
  sources: CandidateSource[];
  maxResults: number;
}

export interface ImportCandidatePayload {
  requisitionId?: string;
  source: CandidateSource;
  externalId: string;
  profileData: CandidateProfileData;
}

export interface ScreenResumePayload {
  candidateId: string;
  requisitionId: string;
  resumeUrl: string;
  evaluationRubricId: string;
}

export interface GenerateAssessmentPayload {
  candidateId: string;
  requisitionId: string;
  assessmentType: AssessmentType;
  evaluationRubricId: string;
}

export interface ScheduleInterviewPayload {
  candidateId: string;
  requisitionId: string;
  interviewType: InterviewType;
  interviewers: Interviewer[];
  duration: number; // minutes
  proposedTimes: ProposedTime[];
  location?: InterviewLocation;
}

export interface SendReminderPayload {
  candidateId: string;
  reminderType: ReminderType;
  channel: 'email' | 'sms';
  message: string;
  relatedEventId?: string;
}

export interface UpdateATSStatusPayload {
  candidateId: string;
  externalCandidateId: string;
  newStage: string;
  notes?: string;
}

export interface SyncCandidatePayload {
  candidateId: string;
  direction: 'push' | 'pull';
  integration: string;
}

export interface PrepareOfferPayload {
  candidateId: string;
  requisitionId: string;
  offerDetails: OfferDetails;
}

export interface SendOfferPayload {
  candidateId: string;
  offerId: string;
  deliveryMethod: 'email' | 'portal';
  expirationDays: number;
}

export interface UpdateGuidelinesPayload {
  guidelinesId: string;
  updates: TaskGuidelinesUpdate[];
  reasoning: string;
}

export interface GenerateReportPayload {
  reportType: ReportType;
  parameters: Record<string, unknown>;
  format: 'pdf' | 'csv' | 'json';
}

// =============================================================================
// SUPPORTING TYPES
// =============================================================================

export interface Attachment {
  name: string;
  url: string;
  mimeType: string;
}

export interface CandidateSearchQuery {
  keywords: string[];
  titles?: string[];
  skills?: string[];
  locations?: string[];
  experienceYears?: { min?: number; max?: number };
  education?: string[];
  companies?: string[];
  excludeCompanies?: string[];
}

export type CandidateSource = 'linkedin' | 'indeed' | 'glassdoor' | 'ats' | 'referral' | 'direct';

export interface CandidateProfileData {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  linkedInUrl?: string;
  resumeUrl?: string;
  currentTitle?: string;
  currentCompany?: string;
  skills?: string[];
  experience?: ExperienceEntry[];
  education?: EducationEntry[];
}

export interface ExperienceEntry {
  title: string;
  company: string;
  startDate: string;
  endDate?: string;
  description?: string;
}

export interface EducationEntry {
  degree: string;
  institution: string;
  graduationDate?: string;
  field?: string;
}

export type AssessmentType =
  | 'RESUME_SCREEN'
  | 'SKILLS_MATCH'
  | 'EXPERIENCE_FIT'
  | 'CULTURE_FIT'
  | 'COMMUNICATION'
  | 'TECHNICAL_SCREEN';

export type InterviewType = 'phone_screen' | 'video' | 'onsite' | 'technical' | 'panel' | 'final';

export interface Interviewer {
  name: string;
  email: string;
  role: string;
}

export interface ProposedTime {
  startTime: Date;
  endTime: Date;
  timezone: string;
}

export interface InterviewLocation {
  type: 'video' | 'phone' | 'in_person';
  details: string; // Video link, phone number, or address
}

export type ReminderType = 'interview_reminder' | 'follow_up_reminder' | 'document_request';

export interface OfferDetails {
  title: string;
  department: string;
  startDate: Date;
  salary: {
    amount: number;
    currency: string;
    frequency: 'annual' | 'hourly';
  };
  bonus?: {
    amount: number;
    type: 'signing' | 'annual' | 'performance';
  };
  equity?: {
    amount: number;
    vestingSchedule: string;
  };
  benefits?: string[];
  otherTerms?: string;
}

export interface TaskGuidelinesUpdate {
  path: string; // JSON path to the field being updated
  operation: 'add' | 'update' | 'remove';
  value?: unknown;
}

export type ReportType =
  | 'pipeline_summary'
  | 'source_effectiveness'
  | 'time_to_fill'
  | 'conversion_rates'
  | 'teleoperator_activity';

// =============================================================================
// TASK PAYLOAD UNION
// =============================================================================

export type TaskPayload =
  | SendEmailPayload
  | SendLinkedInMessagePayload
  | SendFollowUpPayload
  | SearchCandidatesPayload
  | ImportCandidatePayload
  | ScreenResumePayload
  | GenerateAssessmentPayload
  | ScheduleInterviewPayload
  | SendReminderPayload
  | UpdateATSStatusPayload
  | SyncCandidatePayload
  | PrepareOfferPayload
  | SendOfferPayload
  | UpdateGuidelinesPayload
  | GenerateReportPayload;

// =============================================================================
// MAIN TASK TYPE
// =============================================================================

export interface Task {
  id: string;
  tenantId: string;
  requisitionId?: string;

  // Task type and payload
  type: TaskType;
  payload: TaskPayload;

  // Inner loop tracking
  innerLoopId?: string;
  iterations: number;
  converged: boolean;

  // Approval workflow
  status: TaskStatus;
  effectful: boolean;
  escalationReason?: EscalationReasonType;

  // Approval metadata
  approvedBy?: string;
  approvedAt?: Date;
  rejectedBy?: string;
  rejectedAt?: Date;
  rejectionReason?: string;

  // Execution
  executedAt?: Date;
  executionResult?: Record<string, unknown>;
  executionError?: string;

  // Priority and scheduling
  priority: Priority;
  scheduledFor?: Date;
  expiresAt?: Date;

  createdAt: Date;
  updatedAt: Date;
}

// =============================================================================
// TASK EFFECTFULNESS CONFIGURATION
// =============================================================================

/**
 * Defines which task types are effectful (have real-world impact)
 * and therefore require approval before execution.
 */
export const EFFECTFUL_TASK_TYPES: TaskType[] = [
  'SEND_EMAIL',
  'SEND_LINKEDIN_MESSAGE',
  'SEND_FOLLOW_UP',
  'SCHEDULE_INTERVIEW',
  'SEND_REMINDER',
  'UPDATE_ATS_STATUS',
  'SEND_OFFER',
];

/**
 * Task types that are always safe to execute without approval
 */
export const SANDBOX_TASK_TYPES: TaskType[] = [
  'SEARCH_CANDIDATES',
  'SCREEN_RESUME',
  'GENERATE_ASSESSMENT',
  'GENERATE_REPORT',
  'UPDATE_GUIDELINES', // Still needs inner loop convergence
];

/**
 * Check if a task type is effectful
 */
export function isEffectfulTaskType(type: TaskType): boolean {
  return EFFECTFUL_TASK_TYPES.includes(type);
}
